swagger: "2.0"
info:
  version: "1.0.0"
  title: "Redact API"
host: "localhost:8001"
tags:
- name: "redact-api"
  description: "Everything about redact-api"

schemes:
- "http"
paths:
  /health/:
    get:
      tags:
      - "redact-api"
      summary: "Returns the health of the service"
      description: ""
      produces:
      - "application/json"
      responses:
        "200":
          description: "Status Ok"
          schema:
            $ref: "#/definitions/Health"
        "404":
          description: "Not found"
          schema:
            $ref: "#/definitions/ErrorInterface"
        "500":
          description: "Internal server exception"
          schema:
            $ref: "#/definitions/ErrorInterface"
        "503":
          description: "Service un-available"
  
  /redact/:
    post:
      tags:
      - "redact-api"
      summary: "Redacts the given JSON"
      description: ""
      produces:
      - "application/json"
      consumes:
      - "application/json"
      parameters:
        - in: body
          name: body
          description: "Redacts the given JSON"
          schema:
            type: "object"
            properties:
              json_to_redact:
                type: "object"
              redact_regexes:
                type: "array"
                items: 
                  $ref: "#/definitions/RedactRegexes"
              redact_completely:
                type: "array"
                items: 
                  type: "string"
  
      responses:
        "200":
          description: "Status Ok"
          schema:
            type: "object"
        "400":
          description: "Bad request"
          schema:
            $ref: "#/definitions/ErrorInterface"
        "404":
          description: "Not found"
          schema:
            $ref: "#/definitions/ErrorInterface"
        "500":
          description: "Internal server exception"
          schema:
            $ref: "#/definitions/ErrorInterface"
        "503":
          description: "Service un-available"

definitions:
  Health:
    type: "object"
    properties:
      TimeStampUTC:
        type: "string"
      ServiceName:
        type: "string"
      ServiceProvider:
        type: "string"
      ServiceVersion:
        type: "string"
      ServiceStatus:
        type: "string"
      ServiceStartTimeUTC:
        type: "string"
      Uptime:
        type: "integer"
      InboundInterfaces:
        type: "array"
        items:
          $ref: "#/definitions/InboundInterface"
      OutboundInterfaces:
        type: "array"
        items:
          $ref: "#/definitions/OutboundInterface"
          
  OutboundInterface:
    type: "object"
    properties:
      ApplicationName:
        type: "string"
      TimeStampUTC:
        type: "string"
      URLs:
        type: "array"
        items:
          type: "string"
      ConnectionStatus:
        type: "string"
  
  InboundInterface:
    type: "object"
    properties:
      ApplicationName:
        type: "string"
      TimeStampUTC:
        type: "string"
      Hostname:
        type: "string"
      ConnectionStatus:
        type: "string"
      Address:
        type: "string"
      OS:
        type: "string"
        
  ErrorInterface:
    type: "object"
    properties:
      Status:
        type: "string"
      Code:
        type: "string"
      Error:
        type: "string"
  
  ReductResponse:
    type: "object"
    
  RedactInterface:
    type: "object"
    properties:
      json_to_redact:
        type: "object"
      redact_completely:
        type: "array"
        items:
          type: "string"
      redact_regexes:
        type: array
        items: 
          $ref: "#/definitions/RedactRegexes"
  
  RedactRegexes:
    type: object
    properties:
      path:
        type: "string"
      regexes:
        type: "array"
        items:
          type: "string"
        